name: Image_Alpine_NginX

on: [push, pull_request]

jobs:
  testing:
  
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./angular
    
    strategy: 
        matrix:
            node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
    
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +%s)"

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - run: |
          npm ci
          npm run build
          npm test -- --watch=false --browsers=ChromeHeadless
        env:
          ci: true

  building:

    needs: ['testing']
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./angular
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: |
          npm ci
          npm run build --prod 
        
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            my-docker-hub-namespace/my-docker-hub-repository
            ghcr.io/${{ github.repository }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

