name: Image_Alpine_NginX+Angular

on: [push, pull_request]

jobs:
  testing:
  
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./angular
    
    strategy: 
        matrix:
            node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
            node-version: ${{ matrix.node-version }}
      - run: |
          npm install
          npm run build
          npm test -- --watch=false --browsers=ChromeHeadless
        env:
          ci: true
          
  #building:
